export default {
  index: "Overview",
  architecture: "Architecture",
  components: "Components",
  "error-boundaries": "Error Boundaries",
  "lazy-loading": "Lazy Loading",
  observability: "Observability",
  resilience: "Resilience",
  "ai-safety": "AI Safety",
  chaos: "Chaos Testing",
  "resource-index": "Resource Index",
  "resource-detail": "Resource Detail",
  dashboard: "Dashboard",
  authentication: "Authentication",
  "mobile-first": "Mobile-First",
}
